In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
#sample text data
texts=['This is the first document',
      'This  document is the second document',
      'And this id the third one',
       'Is this the first document']

Tokenize the text:Split your text into individual words or tokens.

create a vocabulary build a vocabulary mapping each unique word/token to an integer index.

convert text to sequences: replace each word/token in the text with its corresponding integer index based on the vocabulary.

In [3]:
tokenizer=Tokenizer()

tokenizer.fit_on_texts(texts)
word_index=tokenizer.word_index

In [4]:
word_index

{'this': 1,
 'the': 2,
 'document': 3,
 'is': 4,
 'first': 5,
 'second': 6,
 'and': 7,
 'id': 8,
 'third': 9,
 'one': 10}

In [5]:
sequences = tokenizer.texts_to_sequences(texts)

In [6]:
sequences

[[1, 4, 2, 5, 3], [1, 3, 4, 2, 6, 3], [7, 1, 8, 2, 9, 10], [4, 1, 2, 5, 3]]

tokenize the text using Tokenizer and convert it into sequences of integers,pad the sequences to ensure they all have the same length.

then create an embedidng matrix using Embedding layer,where each word index in the  sequences is mapped to a dense vector representation



In [11]:
#step3:pad sequences{optional}
#Ensure all sequences have the same length by padding then with zeros or truncating then,
max_sequence_length=max([len(seq)for seq in sequences])
sequences_padded=pad_sequences(sequences,max_sequence_length,padding='post')


In [12]:
sequences_padded

array([[ 1,  4,  2,  5,  3,  0],
       [ 1,  3,  4,  2,  6,  3],
       [ 7,  1,  8,  2,  9, 10],
       [ 4,  1,  2,  5,  3,  0]])

In [18]:
#step 4: Apply Embedded layer
vocab_size=len(word_index)+1#Add 1 for the padding token
embedding_dim=10 #Dimensionality of the dense embedding,how many features we want to get
embedding_matrix=tf.keras.layers.Embedding(vocab_size,embedding_dim)(sequences_padded)

In [19]:
vocab_size

11

In [20]:
embedding_matrix

<tf.Tensor: shape=(4, 6, 10), dtype=float32, numpy=
array([[[ 0.00701129,  0.02009818,  0.00326275,  0.01492188,
          0.03935621, -0.00760423, -0.00146579,  0.03328215,
          0.03673149,  0.03602679],
        [ 0.04040361, -0.01636294,  0.0281814 ,  0.02929983,
         -0.0008631 , -0.02536528,  0.03114644,  0.02887237,
          0.01377065, -0.04836928],
        [-0.03494245, -0.00624971,  0.0339229 ,  0.02501868,
         -0.03530798, -0.02711538, -0.00470088, -0.03875319,
          0.02784597,  0.03366885],
        [ 0.04779335,  0.04108945,  0.01618012, -0.0264813 ,
          0.00070152,  0.03477964,  0.00808493, -0.00257443,
         -0.03787651, -0.04506816],
        [ 0.02148118,  0.00810901,  0.01190414,  0.02135411,
         -0.0082275 , -0.00447562, -0.01178296,  0.01784093,
         -0.02615254, -0.02689477],
        [-0.01592624,  0.01468157, -0.01513099, -0.02661245,
          0.03715931, -0.01974171,  0.04762168,  0.00067891,
          0.02022967, -0.03037271]],

In [22]:
#print the embedding matrix shape
print(embedding_matrix.shape)  #Output:(num_samples,max_sequence_length,embedding_dim)

(4, 6, 10)


Dimension 1(4): This dimension corresponds to the number of samples in your input data

Dimension 2(6):represent the length of the sequences after padding

Dimension 3(10):dimensionality of the dense embedding vectors