In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews=['nice food',
       'amazing restaurant',
       'too good',
       'just loves it!',
       'will go again',
       'horrible food',
       'never go there',
       'poor service',
       'poor quality',
       'needs improvment']
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot('amazing_restaurant',30)

[26, 13]

In [4]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size)for d in reviews]

In [5]:
max_length=4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[ 8 17  0  0]
 [26 13  0  0]
 [14 18  0  0]
 [19  5 23  0]
 [12 16 12  0]
 [17 17  0  0]
 [17 16  2  0]
 [ 3 11  0  0]
 [ 3  8  0  0]
 [ 5 19  0  0]]


In [6]:
embedded_vector_size=5

model=Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

C:\Users\pc\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [7]:
x=padded_reviews
y=sentiment

In [8]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [9]:
model.fit(x,y,epochs=50,verbose=0)   #verbose-no output will be displayed on the console

In [10]:
#valuate the model
loss,accuracy=model.evaluate(x,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.6262


1.0

In [11]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [12]:
weights[13]

array([-0.07420943,  0.09515934, -0.07277209, -0.03266012,  0.08708286],
      dtype=float32)

In [13]:
weights[16]

array([ 0.02757963,  0.04211792,  0.04105301, -0.03442113, -0.03165678],
      dtype=float32)